// Writes docs/options.schema.json from src/schema.js (every option: type, range, names, where it shows, what it costs).
//   node tools/schema.mjs          write it
//   node tools/schema.mjs --check  fail if the file is out of date (run after changing DEFAULTS or the schema)
import fs from "node:fs";
import { SCHEMA } from "../src/schema.js";

const out = new URL("../docs/options.schema.json", import.meta.url);
const json = JSON.stringify({
  about: "Every Hinagata option by path (as in DEFAULTS, src/options.js). Generated by tools/schema.mjs from src/schema.js: edit those, not this file.",
  fields: {
    type: "number | boolean | color (#rrggbb or #rrggbbaa) | enum | image (path or data URL) | json (arrays, or any shape)",
    soft: "the range is a guess from the default; values outside it are allowed",
    tier: "main = shown in the editor / advanced = folded (fine-tuning)",
    cost: "what a change rebuilds: instant | paint (materials or painted attributes) | hair | clothes | body (body, clothes and hair)",
    apply: "the avatar method that applies it without a rebuild, or null",
    alsoShapes: "an instant change that also moves a shape on the next build",
    order: "main values: their place in the editor's panels",
    when: "{ path: value }: the value only matters when those other values are set so",
  },
  options: SCHEMA,
}, null, 1) + "\n";
if (process.argv.includes("--check")) {
  const now = fs.existsSync(out) ? fs.readFileSync(out, "utf8") : "";
  if (now !== json) { console.error("docs/options.schema.json is out of date: run node tools/schema.mjs"); process.exit(1); }
  console.log("docs/options.schema.json is up to date");
} else {
  fs.writeFileSync(out, json);
  const all = Object.values(SCHEMA), n = (f) => all.filter(f).length;
  console.log(`wrote docs/options.schema.json: ${all.length} options (${n((e) => e.tier === "main")} main, ${n((e) => e.tier === "advanced")} advanced, ${n((e) => e.soft)} with a guessed range)`);
}
